-- 北大機會雷達 v0.4-C public source sample
-- 執行前請先執行 docs/SUPABASE_SCHEMA.sql。
-- 目的：用真實官方公開來源測試 source_url -> Supabase competitions -> 前端列表／詳情頁。
-- 本檔不取代 docs/SUPABASE_SEED.sql；可在 demo seed 之後額外執行。

delete from public.competitions
where source_item_key in (
  'ntpu_osa_extracurricular:2026-04-15:kingcar-summer-sponsorship',
  'ntpu_osa_extracurricular:2026-04-16:yunlin-singing-selection',
  'ntpu_osa_extracurricular:2026-04-16:airtac-public-service-funding'
);

insert into public.competitions (
  id,
  title,
  organizer,
  source_url,
  source_name,
  source_type,
  source_posted_date,
  source_fetched_at,
  source_content_hash,
  source_item_key,
  series_key,
  instance_key,
  deadline,
  opportunity_type,
  topic_areas,
  category_tags,
  skill_tags,
  submission_types,
  first_stage_deliverables,
  eligibility_text,
  school_limit,
  department_limit,
  grade_limit,
  prize_text,
  reward_types,
  max_prize_amount,
  summary,
  special_notes,
  participation_text,
  schedule,
  judging_text,
  status
) values
(
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
  '2026 金車曙光暑假物資贊助計劃',
  '金車文教基金會',
  'https://new.ntpu.edu.tw/osa/news/69df3775e915ff2abd62481e/2026%E9%87%91%E8%BB%8A%E6%9B%99%E5%85%89%E6%9A%91%E5%81%87%E7%89%A9%E8%B3%87%E8%B4%8A%E5%8A%A9%E8%A8%88%E5%8A%83',
  '國立臺北大學學務處課外組公告',
  'manual_public_source',
  '2026-04-15',
  '2026-06-26T00:00:00+08:00',
  'manual-ntpu-kingcar-2026-summer-v1',
  'ntpu_osa_extracurricular:2026-04-15:kingcar-summer-sponsorship',
  'kingcar-summer-sponsorship',
  '2026-summer',
  '2026-05-31',
  '補助／計畫',
  array['社會／永續','不限／不適用'],
  array['校園生活','公共議題'],
  array['企劃','寫作'],
  array['申請表','企劃書'],
  array['申請資料','服務行動規劃'],
  '全臺高中職暨大專院校學生、社團或五人以上團隊，需具在學學生身分。',
  '大專院校',
  '不限',
  '大一、大二、大三、大四、碩一、碩二',
  '物資贊助約 3,000 元',
  array['實體資源','補助'],
  3000,
  '支持學生於暑假期間推動服務學習與公益行動，提供物資協助。',
  array['申請截止日為 2026/5/31。','完整物資內容與申請規則需確認官方公告。'],
  '社團或五人以上團隊',
  '[{"date":"5/31","label":"申請截止"}]'::jsonb,
  null,
  'published'
),
(
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2',
  '2026 雲林縣歌唱人才培訓計畫－雲耀星聲歌唱選秀大賞',
  '雲林縣政府',
  'https://new.ntpu.edu.tw/osa/news?tag=%E8%AA%B2%E5%A4%96%E7%B5%84,%E8%AA%B2%E6%8C%87%E7%B5%84&title=%E8%AA%B2%E5%A4%96%E7%B5%84',
  '國立臺北大學學務處課外組公告',
  'manual_public_source',
  '2026-04-16',
  '2026-06-26T00:00:00+08:00',
  'manual-ntpu-yunlin-singing-2026-v1',
  'ntpu_osa_extracurricular:2026-04-16:yunlin-singing-selection',
  'yunlin-singing-selection',
  '2026',
  null,
  '比賽',
  array['設計／創作','其他'],
  array['校園生活'],
  array['簡報'],
  array['申請表','影片'],
  array['報名資料','影音或表演相關資料'],
  '官方列表公告未完整列明資格，報名前需確認官方簡章。',
  '需確認',
  '不限',
  null,
  '獎項與培訓資源依官方公告為準',
  array['曝光','證書'],
  null,
  '轉知雲林縣歌唱人才培訓與選秀活動，適合有表演與影音成果的學生評估。',
  array['資格、賽程與繳交格式需以官方公告為準。'],
  '依官方公告',
  '[{"date":"4/16","label":"北大公告轉知"}]'::jsonb,
  null,
  'published'
),
(
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3',
  '114-2 學期亞德客有美公益活動經費補助',
  '亞德客有美公益團體',
  'https://new.ntpu.edu.tw/osa/news?tag=%E8%AA%B2%E5%A4%96%E7%B5%84,%E8%AA%B2%E6%8C%87%E7%B5%84&title=%E8%AA%B2%E5%A4%96%E7%B5%84',
  '國立臺北大學學務處課外組公告',
  'manual_public_source',
  '2026-04-16',
  '2026-06-26T00:00:00+08:00',
  'manual-ntpu-airtac-public-service-114-2-v1',
  'ntpu_osa_extracurricular:2026-04-16:airtac-public-service-funding',
  'airtac-public-service-funding',
  '114-2',
  '2026-05-11',
  '補助／計畫',
  array['社會／永續','其他'],
  array['校園生活','公共議題'],
  array['企劃'],
  array['申請表','企劃書','證明文件'],
  array['活動經費補助申請資料','公益活動企劃或說明'],
  '官方列表公告未完整列明資格，申請前需確認官方簡章。',
  '需確認',
  '不限',
  null,
  '活動經費補助，金額依公告與審查結果為準',
  array['補助'],
  null,
  '受理公益活動經費補助申請，適合正在規劃校園或社會服務行動的學生團隊確認。',
  array['受理申請至 2026/5/11。','補助資格、金額與核銷方式需以官方公告為準。'],
  '依官方公告',
  '[{"date":"5/11","label":"受理申請截止"}]'::jsonb,
  null,
  'published'
)
on conflict (id) do update set
  title = excluded.title,
  organizer = excluded.organizer,
  source_url = excluded.source_url,
  source_name = excluded.source_name,
  source_type = excluded.source_type,
  source_posted_date = excluded.source_posted_date,
  source_fetched_at = excluded.source_fetched_at,
  source_content_hash = excluded.source_content_hash,
  source_item_key = excluded.source_item_key,
  series_key = excluded.series_key,
  instance_key = excluded.instance_key,
  deadline = excluded.deadline,
  opportunity_type = excluded.opportunity_type,
  topic_areas = excluded.topic_areas,
  category_tags = excluded.category_tags,
  skill_tags = excluded.skill_tags,
  submission_types = excluded.submission_types,
  first_stage_deliverables = excluded.first_stage_deliverables,
  eligibility_text = excluded.eligibility_text,
  school_limit = excluded.school_limit,
  department_limit = excluded.department_limit,
  grade_limit = excluded.grade_limit,
  prize_text = excluded.prize_text,
  reward_types = excluded.reward_types,
  max_prize_amount = excluded.max_prize_amount,
  summary = excluded.summary,
  special_notes = excluded.special_notes,
  participation_text = excluded.participation_text,
  schedule = excluded.schedule,
  judging_text = excluded.judging_text,
  status = excluded.status,
  updated_at = now();
