-- 北大機會雷達 v0.3-C demo seed
-- 執行前請先執行 docs/SUPABASE_SCHEMA.sql。
-- 本 seed 會移除 example.com demo 資料後重建 9 筆 published opportunities。

delete from public.competitions
where source_url like 'https://example.com/%';

insert into public.competitions (
  id,
  title,
  organizer,
  source_url,
  source_name,
  source_type,
  source_posted_date,
  source_fetched_at,
  source_content_hash,
  source_item_key,
  series_key,
  instance_key,
  deadline,
  opportunity_type,
  topic_areas,
  category_tags,
  skill_tags,
  submission_types,
  first_stage_deliverables,
  eligibility_text,
  school_limit,
  department_limit,
  grade_limit,
  prize_text,
  reward_types,
  max_prize_amount,
  summary,
  special_notes,
  participation_text,
  schedule,
  judging_text,
  status
) values
(
  '11111111-1111-4111-8111-111111111111',
  'AI 校園創新應用競賽',
  '未來創新基金會',
  'https://example.com/ai-campus-guide',
  'demo seed',
  'manual_demo',
  '2026-06-25',
  '2026-06-25T00:00:00+08:00',
  'demo-ai-campus-innovation',
  'demo:ai-campus-innovation',
  'ai-campus-innovation',
  '2026',
  '2026-07-15',
  '比賽',
  array['科技／程式','創業／新創'],
  array['AI','校園生活','創業'],
  array['企劃','簡報','程式'],
  array['企劃書','簡報','程式／Demo'],
  array['10 頁內企劃書','作品簡報','可附 Demo 連結'],
  '大專院校在學學生可參加，不限科系，可個人或 1–4 人團隊報名。',
  '大專院校',
  '不限',
  '大一、大二、大三、大四、碩一、碩二',
  '最高獎金 100,000 元',
  array['獎金','曝光'],
  100000,
  '鼓勵學生提出能改善校園服務或學習體驗的 AI 應用方案。',
  array['入圍後需到現場簡報。','Demo 可加分，但初賽不強制提交。'],
  '個人或 1–4 人團隊',
  '[{"date":"7/15","label":"報名與初賽資料繳交截止"},{"date":"8/1","label":"公布決賽入圍名單"},{"date":"8/20","label":"現場決賽簡報"}]'::jsonb,
  '創新性、可行性、使用者價值、簡報表現',
  'published'
),
(
  '22222222-2222-4222-8222-222222222222',
  '資料分析商業競賽',
  '城市資料應用協會',
  'https://example.com/data-business',
  'demo seed',
  'manual_demo',
  '2026-06-25',
  '2026-06-25T00:00:00+08:00',
  'demo-data-business-challenge',
  'demo:data-business-challenge',
  'data-business-challenge',
  '2026',
  '2026-08-11',
  '比賽',
  array['商業／企劃','科技／程式'],
  array['金融','AI'],
  array['資料分析','簡報','寫作'],
  array['簡報','企劃書'],
  array['資料分析報告','8 分鐘簡報檔'],
  '大學生與研究生可參加，不限科系，可跨校組隊。',
  '大專院校',
  '不限',
  '大一、大二、大三、大四、碩一、碩二',
  '最高獎金 80,000 元',
  array['獎金','證書'],
  80000,
  '以公開資料提出商業洞察，適合想累積分析作品的學生。',
  array['決賽簡報須說明資料來源與分析限制。','作品不得重複投稿其他競賽。'],
  '2–4 人團隊',
  '[{"date":"8/11","label":"初賽資料繳交截止"},{"date":"8/28","label":"公布決賽入圍名單"}]'::jsonb,
  '洞察品質、資料處理、商業可行性、表達清楚度',
  'published'
),
(
  '33333333-3333-4333-8333-333333333333',
  '金融科技專題提案賽',
  '金融科技推廣中心',
  'https://example.com/fintech-proposal',
  'demo seed',
  'manual_demo',
  '2026-06-25',
  '2026-06-25T00:00:00+08:00',
  'demo-fintech-proposal',
  'demo:fintech-proposal',
  'fintech-proposal',
  '2026',
  '2026-08-20',
  '比賽',
  array['商業／企劃','科技／程式','創業／新創'],
  array['金融','AI','創業'],
  array['企劃','簡報','資料分析'],
  array['企劃書','簡報'],
  array['提案書','決賽簡報'],
  '商管、資工相關科系學生可參加，雙主修符合者可報名。',
  '系所限定',
  '金融系、企業管理學系、資訊工程學系',
  '大二、大三、大四、碩一、碩二',
  '最高獎金 120,000 元',
  array['獎金','曝光'],
  120000,
  '聚焦金融服務創新、風險控管與資料應用的專題提案。',
  array['團隊成員至少一人需具備商管或資工背景。','入圍後須配合成果展示。'],
  '2–5 人團隊',
  '[{"date":"8/20","label":"報名截止"},{"date":"9/5","label":"入圍公告"}]'::jsonb,
  '金融場景理解、技術可行性、風險意識、展示完整度',
  'published'
),
(
  '44444444-4444-4444-8444-444444444444',
  '青年法政評論徵文獎',
  '公共政策研究會',
  'https://example.com/law-policy-essay',
  'demo seed',
  'manual_demo',
  '2026-06-25',
  '2026-06-25T00:00:00+08:00',
  'demo-law-policy-essay',
  'demo:law-policy-essay',
  'law-policy-essay',
  '2026',
  '2026-07-30',
  '比賽',
  array['法政／公共議題','人文／寫作'],
  array['法律','公共議題'],
  array['寫作'],
  array['作品集'],
  array['評論文章一篇','學生證明文件'],
  '法律系主修學生限定，需附在學證明。',
  '系所限定',
  '法律系',
  '大一、大二、大三、大四、碩一、碩二',
  '最高獎金 30,000 元',
  array['獎金','證書'],
  30000,
  '鼓勵法律系學生以公共議題為題撰寫評論文章。',
  array['僅限法律系主修，興趣或修課經驗不等同資格。','文章不得已公開發表。'],
  '個人參加',
  '[{"date":"7/30","label":"徵文截止"}]'::jsonb,
  '論證完整度、法政理解、文字表達',
  'published'
),
(
  '55555555-5555-4555-8555-555555555555',
  '北大學生自主學習獎學金',
  '國立臺北大學學務處',
  'https://example.com/ntpu-scholarship',
  'demo seed',
  'manual_demo',
  '2026-06-25',
  '2026-06-25T00:00:00+08:00',
  'demo-ntpu-student-scholarship',
  'demo:ntpu-student-scholarship',
  'ntpu-student-scholarship',
  '2026',
  '2026-07-22',
  '獎學金',
  array['不限／不適用'],
  array['校園生活'],
  array['寫作','企劃'],
  array['申請表','證明文件'],
  array['申請表','自主學習計畫','歷年成績單'],
  '國立臺北大學在學學生可申請，需提出自主學習計畫。',
  '國立臺北大學',
  '不限',
  '大一、大二、大三、大四、碩一、碩二',
  '獎學金 20,000 元',
  array['獎學金'],
  20000,
  '支持北大學生自主學習、專題探索與作品累積。',
  array['需附成績單與在學證明。','獲獎後需提交學習成果摘要。'],
  '個人申請',
  '[{"date":"7/22","label":"申請截止"},{"date":"8/15","label":"審查結果公告"}]'::jsonb,
  null,
  'published'
),
(
  '66666666-6666-4666-8666-666666666666',
  '北聯大跨域學習獎助金',
  '臺北聯合大學系統',
  'https://example.com/tua-scholarship',
  'demo seed',
  'manual_demo',
  '2026-06-25',
  '2026-06-25T00:00:00+08:00',
  'demo-university-alliance-scholarship',
  'demo:university-alliance-scholarship',
  'university-alliance-scholarship',
  '2026',
  '2026-09-03',
  '獎學金',
  array['社會／永續','不限／不適用'],
  array['SDGs','公共議題','校園生活'],
  array['寫作','簡報'],
  array['申請表','證明文件','簡報'],
  array['申請表','跨域學習說明','成果簡報'],
  '臺北聯合大學系統學生可申請，需提出跨校或跨域學習成果。',
  '臺北聯合大學系統',
  '不限',
  '大二、大三、大四、碩一、碩二',
  '獎助金 15,000 元',
  array['獎學金','補助'],
  15000,
  '鼓勵北聯大學生整理跨域學習成果與未來學習規劃。',
  array['需附跨域修課或活動證明。','資料不完整者可能需補件。'],
  '個人申請',
  '[{"date":"9/3","label":"申請截止"}]'::jsonb,
  null,
  'published'
),
(
  '77777777-7777-4777-8777-777777777777',
  'SDGs 校園行動補助計畫',
  '青年永續行動平台',
  'https://example.com/sdgs-action-grant',
  'demo seed',
  'manual_demo',
  '2026-06-25',
  '2026-06-25T00:00:00+08:00',
  'demo-sdgs-action-grant',
  'demo:sdgs-action-grant',
  'sdgs-action-grant',
  '2026',
  '2026-08-05',
  '補助／計畫',
  array['社會／永續','法政／公共議題'],
  array['SDGs','校園生活','公共議題'],
  array['企劃','設計','影片剪輯'],
  array['企劃書','影片'],
  array['行動企劃書','1 分鐘提案影片'],
  '大專院校學生可提案，可組隊執行校園永續行動。',
  '大專院校',
  '不限',
  '大一、大二、大三、大四、碩一、碩二',
  '最高補助 50,000 元',
  array['補助','曝光'],
  50000,
  '支持學生在校園內推動永續、社會參與或公共倡議行動。',
  array['所有隊員需出現在提案影片中。','獲補助後需公開成果紀錄。'],
  '2–6 人團隊',
  '[{"date":"8/5","label":"提案截止"},{"date":"8/25","label":"補助名單公告"}]'::jsonb,
  '問題意識、執行可行性、校園影響力',
  'published'
),
(
  '88888888-8888-4888-8888-888888888888',
  '學生創業原型補助',
  '校園創業支持中心',
  'https://example.com/startup-prototype',
  'demo seed',
  'manual_demo',
  '2026-06-25',
  '2026-06-25T00:00:00+08:00',
  'demo-startup-prototype-fund',
  'demo:startup-prototype-fund',
  'startup-prototype-fund',
  '2026',
  '2026-09-18',
  '補助／計畫',
  array['創業／新創','科技／程式','商業／企劃'],
  array['創業','AI','金融'],
  array['企劃','程式','設計'],
  array['企劃書','程式／Demo','簡報'],
  array['原型計畫書','Demo 截圖或連結','預算表'],
  '資格公告未完整列明，建議報名前確認官方簡章。',
  '需確認',
  null,
  null,
  '最高補助 60,000 元',
  array['補助','實體資源'],
  60000,
  '協助學生將產品構想做成可展示的初版原型。',
  array['補助款需依核定用途支用。','期末需提交成果展示資料。'],
  '個人或團隊',
  '[{"date":"9/18","label":"申請截止"}]'::jsonb,
  null,
  'published'
),
(
  '99999999-9999-4999-8999-999999999999',
  '學生作品集公開徵選',
  '青年創作交流平台',
  'https://example.com/portfolio-showcase',
  'demo seed',
  'manual_demo',
  '2026-06-25',
  '2026-06-25T00:00:00+08:00',
  'demo-portfolio-showcase',
  'demo:portfolio-showcase',
  'portfolio-showcase',
  '2026',
  '2026-07-18',
  '其他',
  array['設計／創作','其他'],
  array['校園生活','創業'],
  array['設計','寫作','影片剪輯'],
  array['作品集','申請表'],
  array['作品集連結','300 字創作說明'],
  '大專院校在學學生可投稿，作品主題不限。',
  '大專院校',
  '不限',
  '大一、大二、大三、大四、碩一、碩二',
  '入選可獲 8,000 元創作獎勵',
  array['獎金','曝光'],
  8000,
  '徵選學生作品集與創作專案，適合想整理作品成果的人。',
  array['作品需為本人或團隊原創。','入選後需同意平台展示作品摘要。'],
  '個人參加',
  '[{"date":"7/18","label":"投稿截止"}]'::jsonb,
  null,
  'published'
)
on conflict (id) do update set
  title = excluded.title,
  organizer = excluded.organizer,
  source_url = excluded.source_url,
  source_name = excluded.source_name,
  source_type = excluded.source_type,
  source_posted_date = excluded.source_posted_date,
  source_fetched_at = excluded.source_fetched_at,
  source_content_hash = excluded.source_content_hash,
  source_item_key = excluded.source_item_key,
  series_key = excluded.series_key,
  instance_key = excluded.instance_key,
  deadline = excluded.deadline,
  opportunity_type = excluded.opportunity_type,
  topic_areas = excluded.topic_areas,
  category_tags = excluded.category_tags,
  skill_tags = excluded.skill_tags,
  submission_types = excluded.submission_types,
  first_stage_deliverables = excluded.first_stage_deliverables,
  eligibility_text = excluded.eligibility_text,
  school_limit = excluded.school_limit,
  department_limit = excluded.department_limit,
  grade_limit = excluded.grade_limit,
  prize_text = excluded.prize_text,
  reward_types = excluded.reward_types,
  max_prize_amount = excluded.max_prize_amount,
  summary = excluded.summary,
  special_notes = excluded.special_notes,
  participation_text = excluded.participation_text,
  schedule = excluded.schedule,
  judging_text = excluded.judging_text,
  status = excluded.status,
  updated_at = now();
